### ISSUE TITLE
# 2.1.2 Diagramas detallados 

### ISSUE THREAD

**Issue by ghost** [aquintero10/Gerencia#14]
Los diagramas deben incluir el detalle de cada actividad y situación 

Entregables: Presentación con diagramas realizados

**Comment by Cronoxer** [comment]
29 oct – Entrega de diagramas detallados

**Comment by Cronoxer** [comment]
29 oct – Entrega de diagramas detallados

**Comment by ghost** [comment]
29 oct – Entrega de diagramas detallados
